spring:

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: food-service
              uri: lb://FOOD-SERVICE
              predicates:
                - Path=/api/v1/food/**

            - id: category-service
              uri: lb://FOOD-SERVICE
              predicates:
                  - Path=/api/v1/categories,/api/v1/categories/**

            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customer/**

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
server:
  port: 7000